# Use the same base image as FastAPI
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install -r requirements.txt

# Start the Celery worker
CMD ["celery", "-A", "app.workers.celery_app", "worker", "--loglevel=info"]
